### ISSUE TITLE
Interested in contributing to iQL project for Japanese Mahjong

### ISSUE THREAD

**Issue by ZhouLixuanwu** [Cryolite/tsumonya#1]
Hello Cryolite,

I noticed that you are starting new work on iQL for Japanese Mahjong and have created a new repository for it. I would like to offer my help as I have some experience with Japanese Mahjong and I am interested in contributing to this project. Additionally, I have experience with implementing iQL in Starcraft2 AI.

I recently obtained my master's degree in GIS from UIUC, and I will be starting my Ph.D. in AI at UCSD this May.

Please let me know if there is anything specific you need help with, or if you have any suggestions on how I could get involved.

Thank you for your time and consideration. I look forward to hearing back from you.

Best regards,
Lixuanwu

**Comment by Cryolite** [comment]
Hi Lixuanwu Zhou,

Thank you very much for your interest in my repositories. I believe that offline RL is an RL method with great potential for future development, and I find its application to game AI, such as developing mahjong AI, to be very intriguing. In particular, IQL is a SotA method in terms of performance on D4RL datasets, so I have adopted it with high expectations. In this context, having the support of someone with domain knowledge in Japanese mahjong and experience in developing game AI using IQL would be extremely reassuring. So, your help is more than welcome.

Please feel free to ask any questions or seek clarification on anything related to my repositories or projects as you contribute. I will do my best to provide sincere and helpful answers.

By the way, this repository was created because extremely fast score calculation was required as part of the necessary modules for mahjong AI development. The central repository for mahjong AI is [kanachan](https://github.com/Cryolite/kanachan), so for discussions, questions, or contributions related to mahjong AI in general, I would appreciate it if you could create a new thread in the [discussion section of kanachan](https://github.com/Cryolite/kanachan/discussions). Also, I would like to close this issue with this response, so thank you for your understanding.
